Repository zaphiro-technologies/protobuf, pull requests merged in 2025-05, with the labels that each got.

#94 Add auto-approve & auto-merge Dependabot PRs workflow
  .github/workflows/approve-and-merge.yaml
  RELEASE_NOTES.md
Labels: ci

#98 Add event test service event source type
  RELEASE_NOTES.md
  docs/event.proto.md
  docs/fault.proto.md
  go/grid/v1/event.pb.go
  go/grid/v1/fault.pb.go
  python/zaphiro/grid/v1/event_pb2.py
  python/zaphiro/grid/v1/event_pb2.pyi
  python/zaphiro/grid/v1/fault_pb2.py
  python/zaphiro/grid/v1/fault_pb2.pyi
  zaphiro/grid/v1/event.proto
  zaphiro/grid/v1/fault.proto
Labels: feature

#96 Add blacklist message
  RELEASE_NOTES.md
  docs/blacklist.proto.md
  docs/task.proto.md
  go/platform/v1/blacklist.pb.go
  go/platform/v1/task.pb.go
  python/zaphiro/platform/v1/blacklist_pb2.py
  python/zaphiro/platform/v1/blacklist_pb2.pyi
  zaphiro/platform/v1/blacklist.proto
  zaphiro/platform/v1/task.proto
Labels: feature

#100 `Event` message: deprecate `sourceId` and `sourceType` and move to headers
  RELEASE_NOTES.md
  docs/device_event.proto.md
  docs/event.proto.md
  docs/fault.proto.md
  docs/grid_event.proto.md
  go/grid/v1/event.pb.go
  go/grid/v1/fault.pb.go
  python/zaphiro/grid/v1/event_pb2.py
  zaphiro/grid/v1/device_event.proto
  zaphiro/grid/v1/event.proto
  zaphiro/grid/v1/fault.proto
  zaphiro/grid/v1/grid_event.proto
Labels: refactor
